apiVersion: pbom.dev/v1alpha1
kind: PlatformRelease
metadata:
  name: 1.2.0
spec:
  components:
    alloy: 1.10.0
    argo-rollouts: 1.8.3
    argocd: 2.14.20
    cert-manager: 1.18.2
    crossplane: 2.0.2
    external-dns: 0.18.0
    external-secrets: 0.19.2
    gatekeeper: 3.20.1
    grafana: 13.2.2
    ingress-nginx: 1.13.1
    istio: 1.27.1
    keda: 2.17.2
    kubernetes: 1.36.1
    kyverno: 1.15.1
    loki: 3.5.3
    metrics-server: 0.8.0
    opencost: 1.121.3
    opentelemetry-operator: 0.132.0
    prometheus: 3.5.0
    vault: 1.20.2
    velero: 1.18.4
  date: "2026-10-08"
  offerings:
  - gitops
  - traffic
  - secrets
  - policy
  - monitoring
  - autoscaling
  - recovery
  - costs
  summary: Dev platform snapshot from kind simulation
  version: 1.2.0
