components:
  argocd: quay.io/argoproj/argocd:v2.11.13
  argo-rollouts: quay.io/argoproj/argo-rollouts:v1.7.2
  crossplane: xpkg.crossplane.io/crossplane/crossplane:v1.19.1
  velero: docker.io/velero/velero:v1.18.4
  istio: docker.io/istio/pilot:1.24.6
  ingress-nginx: registry.k8s.io/ingress-nginx/controller:v1.12.1
  external-dns: registry.k8s.io/external-dns/external-dns:v0.15.1
  prometheus: quay.io/prometheus/prometheus:v2.55.1
  grafana: docker.io/grafana/grafana:13.2.2
  loki: docker.io/grafana/loki:3.3.2
  alloy: docker.io/grafana/alloy:v1.7.1
  cert-manager: quay.io/jetstack/cert-manager-controller:v1.16.4
  kyverno: ghcr.io/kyverno/kyverno:v1.13.4
  external-secrets: ghcr.io/external-secrets/external-secrets:v0.14.4
  vault: docker.io/hashicorp/vault:1.18.5
  keda: ghcr.io/kedacore/keda:2.16.0
  metrics-server: registry.k8s.io/metrics-server/metrics-server:v0.7.2
  opencost: quay.io/opencost/opencost:1.121.3
  gatekeeper: docker.io/openpolicyagent/gatekeeper:v3.18.2