package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"sigs.k8s.io/yaml"
)

// kustomizeMarker starts every kustomization.yaml pbom writes, so pbom only
// ever rewrites its own files.
const kustomizeMarker = "# Generated by pbom."

type configMapGenerator struct {
	Name  string   `json:"name"`
	Files []string `json:"files"`
}

type kustomization struct {
	APIVersion       string               `json:"apiVersion"`
	Kind             string               `json:"kind"`
	Namespace        string               `json:"namespace"`
	GeneratorOptions map[string]bool      `json:"generatorOptions"`
	ConfigMaps       []configMapGenerator `json:"configMapGenerator"`
}

// writeKustomization turns the platform directory into the three ConfigMaps
// the Helm chart mounts when configMaps.create=false.
func writeKustomization(dir, namespace string) (string, error) {
	path := filepath.Join(dir, "kustomization.yaml")
	if data, err := os.ReadFile(path); err == nil && !strings.HasPrefix(string(data), kustomizeMarker) {
		return "", fmt.Errorf("%s was not generated by pbom; not overwriting it", path)
	}
	if _, err := os.Stat(filepath.Join(dir, "platform.yaml")); err != nil {
		return "", fmt.Errorf("%s has no platform.yaml: %w", dir, err)
	}

	platformFiles := []string{"pbom.yaml=platform.yaml"}
	extra, err := filesIn(dir, ".", ".yaml", ".yml", ".md")
	if err != nil {
		return "", err
	}
	for _, f := range extra {
		if f != "platform.yaml" && f != "kustomization.yaml" {
			platformFiles = append(platformFiles, f)
		}
	}
	k := kustomization{
		APIVersion:       "kustomize.config.k8s.io/v1beta1",
		Kind:             "Kustomization",
		Namespace:        namespace,
		GeneratorOptions: map[string]bool{"disableNameSuffixHash": true},
		ConfigMaps:       []configMapGenerator{{Name: "pbom-platform", Files: platformFiles}},
	}
	for _, sub := range []string{"releases", "components"} {
		files, err := filesIn(dir, sub, ".yaml", ".yml")
		if err != nil {
			return "", err
		}
		if len(files) > 0 {
			k.ConfigMaps = append(k.ConfigMaps, configMapGenerator{Name: "pbom-" + sub, Files: files})
		}
	}
	data, err := yaml.Marshal(k)
	if err != nil {
		return "", err
	}
	header := kustomizeMarker + " Regenerate after adding or removing files with:\n#   pbom kustomize " + dir + "\n"
	return path, os.WriteFile(path, append([]byte(header), data...), 0o644)
}

// filesIn lists files in dir/sub with one of exts, as paths relative to dir.
func filesIn(dir, sub string, exts ...string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(dir, sub))
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		for _, ext := range exts {
			if filepath.Ext(e.Name()) == ext {
				out = append(out, filepath.ToSlash(filepath.Join(sub, e.Name())))
				break
			}
		}
	}
	sort.Strings(out)
	return out, nil
}

// syncKustomization regenerates a pbom-generated kustomization.yaml next to
// the platform file, if there is one.
func syncKustomization(platformPath string) (string, error) {
	dir := filepath.Dir(platformPath)
	data, err := os.ReadFile(filepath.Join(dir, "kustomization.yaml"))
	if err != nil || !strings.HasPrefix(string(data), kustomizeMarker) {
		return "", nil
	}
	var k kustomization
	if err := yaml.Unmarshal(data, &k); err != nil {
		return "", err
	}
	return writeKustomization(dir, k.Namespace)
}

func newKustomizeCmd() *cobra.Command {
	var namespace string
	cmd := &cobra.Command{
		Use:   "kustomize DIR",
		Short: "Regenerate DIR/kustomization.yaml from the files in a platform directory",
		Long: `Regenerate the kustomization.yaml that turns a platform directory created by
"pbom init" into the ConfigMaps the Helm chart mounts: platform.yaml and any
other top-level files (such as exported inventories), releases/*.yaml and
components/*.yaml. Run it after adding or removing files.`,
		Example: `  pbom kustomize pbom-config
  kubectl apply -k pbom-config`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path, err := writeKustomization(args[0], namespace)
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Wrote %s\n", path)
			return nil
		},
	}
	cmd.Flags().StringVarP(&namespace, "namespace", "n", "platform-bom", "namespace pbom is installed in")
	return cmd
}
