apiVersion: v1
kind: Service
metadata:
  name: pbom
  labels:
    app.kubernetes.io/name: platform-bom
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform-bom
  ports:
    - name: http
      port: 80
      targetPort: http
